import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'

export const metadata = {
  title: 'Zam-Zam Pool Kuningan',
  description: 'Generated by create next app',
  icons: {
    icon: [
      '/logo.svg'
    ]
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
      <link rel="logo" href="/logo.svg" />
      </head>
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
